[package]
name = "spacesurvival"
version = "0.0.1"
authors = ["Arne Beer <privat@arne.beer>, Rafael Epplée <raffomania@gmail.com>"]

[dependencies]
uuid = { version = "0.4", features = ["use_std", "serde", "v4", "rustc-serialize"] }
chrono = { version = "0.3", features = ["serde"] }
argon2rs = "0.2"
rocket = "0.2"
rocket_codegen = "0.2"
diesel = { version = "0.11", features = ["postgres", "uuid", "chrono", "serde_json"] }
diesel_codegen = { version = "0.11", features = ["postgres"] }
r2d2 = "0.7.1"
r2d2-diesel = "0.11"
# dotenv = "0.8.0" TODO Make use of this later.
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
lazy_static = "0.2"
validator = "0.4"
validator_derive = "0.4"
jsonwebtoken = "1.1.6"
rustc-serialize = "0.3"
cargo-update = "0.7.1"

[dependencies.rocket_contrib]
version = "0.2"
default-features = false
features = ["json"]
