#!/bin/bash

mkdir -p static
npm install
node_modules/.bin/elm-package install
source venv/bin/activate
./bin/initdb
uwsgi --ini configs/uwsgi.ini &
uwsgi --ini configs/tick-uwsgi.ini &
node_modules/.bin/webpack-dev-server --hot --inline &
watchexec --watch assets "cp -r assets/* static/" &
watchexec --watch client/View "node_modules/.bin/elm-css --output static/css client/Stylesheets.elm"
